import Head from "next/head"
import { useQuery, gql } from "@apollo/client"
import Locations from "../comp/Locations"

const HomePage = () => {
  // wrap the query in the gql template literal
  // gql provides logic for parsing GraphQL queries
  const QUERY = gql`
    query getLocations {
      locations {
        id
        name
        description
        photo
      }
    }
  `

  // `useQuery` automatically executes the query
  // return a result object containing these 3 properties
  const { loading, error, data } = useQuery(QUERY)

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error : {error.message}</p>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>A demo from apollographql.com</div>
      <Locations locations={data.locations} />
    </>
  )
}

export default HomePage
